# Generated by Django 3.2 on 2026-02-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
